### ISSUE TITLE
UI/UX improvements

### ISSUE THREAD

**Issue by soshial** [farfromrefug/aard2-android#3]
1. Icon tint is wrong: <img width=300 src=https://github.com/user-attachments/assets/d9ad34c1-ac0f-40c3-ae1b-bfba211c0314 />
2. Tabs should slide horizontally <img width=300 src=https://github.com/user-attachments/assets/3ccc53dc-9f8a-4a28-921e-f047f8810e40 />
3. Long dictionary title is cut off in the bottom <img width=300 src=https://github.com/user-attachments/assets/96755c45-c063-4616-bf35-0506da41562d />

**Comment by farfromrefug** [comment]
@soshial thanks will fix 1 and 3. 2 was removed on purpose because it broke too many behaviors. I made the choice to have that disabled

**Comment by farfromrefug** [comment]
@soshial new version out!

**Comment by soshial** [comment]
Thanks a lot!
